#! /bin/ksh
# pack the 3270 bitmaps together

set -A f badcommhi box4 boxquestion boxsolid clockleft clockright commjag commlo greater human insert leftarrow lock rightarrow undera upshift

exec 1>3270bm.h

typeset -u u
integer ix=0
for u in ${f[*]}
do	print "#define BM_$u\t$ix"
	ix=ix+1
done
print "#define NBM\t${#f[*]}"

print "#define sl_width\t9"
print "#define sl_height\t17"
print "static char sl[NBM][34] = {"
for i in ${f[*]}
do	tail +4 $i | sed -e '1s/^ */{/' -e '2,$s/^ */ /' -e 's/;$/,/'
done
print "};"
