/* conf.h.  Generated by configure.  */
/*
 * Copyright 2000, 2001, 2002, 2005 by Paul Mattes.
 *   Permission to use, copy, modify, and distribute this software and its
 *   documentation for any purpose and without fee is hereby granted,
 *   provided that the above copyright notice appear in all copies and that
 *   both that copyright notice and this permission notice appear in
 *   supporting documentation.
 *
 * tcl3270 is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the file LICENSE for more details.
 *
 */

/*
 *	conf.h
 *              System-specific #defines for libraries and library functions.
 */


/* Libraries. */
#define HAVE_LIBUTIL 1
#define HAVE_LIBICUI18N 1
#define HAVE_LIBSSL 1

/* Header files. */
#define HAVE_SYS_SELECT_H 1
#define HAVE_PTY_H 1
/* #undef HAVE_LIBUTIL_H */
/* #undef HAVE_UTIL_H */
/* #undef HAVE_TCLEXTEND_H */

/* Uncommon functions. */
#define HAVE_VASPRINTF 1
#define HAVE_FSEEKO 1

/* Optional parts. */
#define X3270_ANSI 1
#define X3270_APL 1
#define X3270_DBCS 1
#define X3270_FT 1
#define X3270_LOCAL_PROCESS 1
#define X3270_TN3270E 1
#define X3270_TRACE 1
