#! /bin/sh
XFILESEARCHPATH=X3270.ad \
 ./x3270 -color -efont 3270-12 \
 -xrm "x3270.neutralBlackColor: frobnitz" \
 -xrm "x3270.blueColor: frobnitz" \
 -xrm "x3270.redColor: frobnitz" \
 -xrm "x3270.pinkColor: frobnitz" \
 -xrm "x3270.greenColor: frobnitz" \
 -xrm "x3270.turquioseColor: frobnitz" \
 -xrm "x3270.yellowColor: frobnitz" \
 -xrm "x3270.neutralWhiteColor: frobnitz" \
 -xrm "x3270.blackColor: frobnitz" \
 -xrm "x3270.deepBlueColor: frobnitz" \
 -xrm "x3270.orangeColor: frobnitz" \
 -xrm "x3270.purpleColor: frobnitz" \
 -xrm "x3270.paleGreenColor: frobnitz" \
 -xrm "x3270.paleTurquoiseColor: frobnitz" \
 -xrm "x3270.greyColor: frobnitz" \
 -xrm "x3270.whiteColor: frobnitz"
